sonar.projectKey=soerenkoehler_rs-cmis-browser-cli
sonar.organization=soerenkoehler
sonar.projectName=rs-cmis-browser-cli
sonar.projectVersion=0.1

sonar.rust.clippy.enabled=true
sonar.rust.lcov.reportPaths=coverage/coverage.lcov

# sonar.verbose=true
# sonar.log.level=DEBUG
